// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2Coder.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2Coder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object alf=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=8;
      Object coder=$fix($invokeMethod(P2Coder.class,"createCoder",true,null,new Object[]{}));
      $line=14;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,coder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"main",$line);
    }
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=19;
      alf=$fix($opIntvlY('a','z'));
      $line=20;
      Object A=$fix($opUnionY(alf,GCollections.asSet("")));
      $line=21;
      Object B=$fix($opCartsY(new Object[]{$opIntvlY(0,2),$opIntvlY(0,4)}));
      $line=22;
      Object C=$fix($opUnionY($opCartsY(new Object[]{A,B}),GCollections.asSet(GCollections.asList(':',GCollections.asList(1,0)))));
      $line=23;
      Object D=$fix($opCartsY(new Object[]{A,A}));
      $line=24;
      Object Q=$fix($opUnionY($opUnionY(D,$opCartsY(new Object[]{D,C})),GCollections.asSet('I','$',"err")));
      $line=25;
      Object \u03A3=$fix($opUnionY(alf,GCollections.asSet(':','$')));
      $line=26;
      Object \u03A3_=$fix($opUnionY($opUnionY($opUnionY(\u03A3,GCollections.asSet('#')),$opIntvlY('A','Z')),$opIntvlY('0','4')));
      $line=27;
      Object q_0=$fix('I');
      $line=28;
      Object F=$fix(GCollections.asSet('$'));
      $line=30;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(P2Coder.class,"\u03B4"),new GMethod(P2Coder.class,"g"),new GMethod(P2Coder.class,"h")});
      if (true) break $try;
      $line=31;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=34;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=35;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=36;
        if ($opEqualY(A,'I')) {
          $line=37;
          $result=GCollections.asList(n,"");
          if (true) break $try;
        }
        else {
          $line=38;
          if (($opEqualY(A,"err")||$opEqualY(A,'$'))) {
            $line=39;
            $result="err";
            if (true) break $try;
          }
        }
      }
      $line=41;
      $rethrow(new RuntimeException("The function \"\u03B4(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object A=$v2.next();
      Object B=$v2.next();
      $line=44;
      if ((($opEqualY(A,"")||$bool((!$opMembrY(A,alf)&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
        $line=45;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=46;
        if ($opMembrY(A,alf)) {
          $line=47;
          if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
            $line=48;
            $result=GCollections.asList(GCollections.asList(A,B),GCollections.asList(':',GCollections.asList(1,0)));
            if (true) break $try;
          }
          else {
            $line=49;
            if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
              $line=50;
              $result=GCollections.asList(A,n);
              if (true) break $try;
            }
            else {
              $line=52;
              $result="err";
              if (true) break $try;
            }
          }
        }
        else {
          $line=55;
          Object a=$fix($opModulY($opAdditY($getArrayValue(B,new Object[]{1,0}),1),3));
          $line=56;
          Object b=$fix($getArrayValue(B,new Object[]{1,1}));
          $line=57;
          if (($opEqualY(n,'$')&&$opEqualY($getArrayValue(B,new Object[]{0}),':'))) {
            $line=58;
            $result="err";
            if (true) break $try;
          }
          else {
            $line=59;
            if ($opEqualY(n,'$')) {
              $line=60;
              $result='$';
              if (true) break $try;
            }
            else {
              $line=61;
              if ($opEqualY(n,':')) {
                $line=62;
                $result="err";
                if (true) break $try;
              }
              else {
                $line=63;
                if (!$opMembrY(n,A)) {
                  $line=64;
                  $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,b)));
                  if (true) break $try;
                }
                else {
                  $line=66;
                  $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=70;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=73;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=74;
        $result="";
        if (true) break $try;
      }
      else {
        $line=75;
        if ($opEqualY(A,'I')) {
          $line=76;
          $result=n;
          if (true) break $try;
        }
        else {
          $line=78;
          $result="";
          if (true) break $try;
        }
      }
      $line=80;
      $rethrow(new RuntimeException("The function \"h(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"h",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v3, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object A=$v4.next();
      Object B=$v4.next();
      $line=83;
      if ((($opEqualY(A,"")||$bool((!$opMembrY(A,alf)&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
        $line=84;
        $result="";
        if (true) break $try;
      }
      else {
        $line=85;
        if ($opMembrY(A,alf)) {
          $line=86;
          if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
            $line=87;
            $result=':';
            if (true) break $try;
          }
          else {
            $line=88;
            if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
              $line=89;
              $result=n;
              if (true) break $try;
            }
            else {
              $line=91;
              $result="";
              if (true) break $try;
            }
          }
        }
        else {
          $line=94;
          if ($opEqualY(n,':')) {
            $line=95;
            $result="";
            if (true) break $try;
          }
          else {
            $line=96;
            if ($opEqualY(n,'$')) {
              $line=97;
              $result=$getArrayValue(B,new Object[]{1,1});
              if (true) break $try;
            }
            else {
              $line=98;
              if ((!$opMembrY(n,A)&&$opEqualY(n,$getArrayValue(B,new Object[]{0})))) {
                $line=99;
                $result="#";
                if (true) break $try;
              }
              else {
                $line=100;
                if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),1))) {
                  $line=101;
                  $result=$invokeMethod(P2Coder.class,"nextToUpper",true,null,new Object[]{n});
                  if (true) break $try;
                }
                else {
                  $line=102;
                  if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),2))) {
                    $line=103;
                    $result=$invokeMethod(P2Coder.class,"toUpper",true,null,new Object[]{n});
                    if (true) break $try;
                  }
                  else {
                    $line=104;
                    if ($opEqualY(n,$getArrayValue(A,new Object[]{0}))) {
                      $line=105;
                      $result=$getArrayValue(A,new Object[]{1});
                      if (true) break $try;
                    }
                    else {
                      $line=106;
                      if ($opEqualY(n,$getArrayValue(A,new Object[]{1}))) {
                        $line=107;
                        $result=$getArrayValue(A,new Object[]{0});
                        if (true) break $try;
                      }
                      else {
                        $line=109;
                        $result=n;
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=112;
      $rethrow(new RuntimeException("The function \"h(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=115;
      $result="";
      if (true) break $try;
      $line=116;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"g",$line);
    }
    return $result;
  }
  public static Object nextToUpper(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=119;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=120;
      r=$cast(Character.class,$fix($opAdditY($opSubtrY($opModulY($opAdditY($opSubtrY(n,'a'),1),26),32),'a')));
      $line=121;
      $result=r;
      if (true) break $try;
      $line=122;
      $rethrow(new RuntimeException("The function \"nextToUpper(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"nextToUpper",$line);
    }
    return $result;
  }
  public static Object toUpper(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=125;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=126;
      r=$cast(Character.class,$fix($opAdditY($opSubtrY($opSubtrY(n,'a'),32),'a')));
      $line=127;
      $result=r;
      if (true) break $try;
      $line=128;
      $rethrow(new RuntimeException("The function \"toUpper(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Coder.class,"toUpper",$line);
    }
    return $result;
  }
}
