// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2Deco.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2Deco {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object alf=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=8;
      Object decoder=$fix(P2Deco.createDecoder());
      $line=14;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,decoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"main",$line);
    }
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=19;
      alf=$fix($opIntvlY('a','z'));
      $line=20;
      Object A=$fix($opUnionY(alf,GCollections.asSet("")));
      $line=21;
      Object B=$fix($opCartsY(new Object[]{$opIntvlY(0,2),$opIntvlY(0,4)}));
      $line=22;
      Object C=$fix($opUnionY($opCartsY(new Object[]{A,B}),GCollections.asSet(GCollections.asList(':',GCollections.asList(1,0)))));
      $line=23;
      Object D=$fix($opCartsY(new Object[]{A,A}));
      $line=24;
      Object Q=$fix($opUnionY($opUnionY(D,$opCartsY(new Object[]{D,C})),GCollections.asSet('I',"num","err")));
      $line=25;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opUnionY(alf,GCollections.asSet(':')),GCollections.asSet('#')),$opIntvlY('A','Z')),$opIntvlY('0','4')));
      $line=26;
      Object \u03A3_=$fix($opUnionY($opUnionY(alf,GCollections.asSet(':')),GCollections.asSet('$')));
      $line=27;
      Object q_0=$fix('I');
      $line=28;
      Object F=$fix(GCollections.asSet("num"));
      $line=30;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(P2Deco.class,"\u03B4"),new GMethod(P2Deco.class,"g"),new GMethod(P2Deco.class,"h")});
      if (true) break $try;
      $line=31;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=36;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=37;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=38;
        if ($opEqualY(A,'I')) {
          $line=39;
          $result=GCollections.asList(n,"");
          if (true) break $try;
        }
        else {
          $line=40;
          if (($opEqualY(A,"err")||$opEqualY(A,"num"))) {
            $line=41;
            $result="err";
            if (true) break $try;
          }
        }
      }
      $line=43;
      $rethrow(new RuntimeException("The function \"\u03B4(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object A=$v2.next();
      Object B=$v2.next();
      $line=46;
      if ((($opEqualY(A,"")||$bool((!$opMembrY(A,alf)&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
        $line=47;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=48;
        if ($opMembrY(A,alf)) {
          $line=49;
          if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
            $line=50;
            $result=GCollections.asList(GCollections.asList(A,B),GCollections.asList(':',GCollections.asList(1,0)));
            if (true) break $try;
          }
          else {
            $line=51;
            if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
              $line=52;
              $result=GCollections.asList(A,n);
              if (true) break $try;
            }
            else {
              $line=54;
              $result="err";
              if (true) break $try;
            }
          }
        }
        else {
          $line=57;
          Object a=$fix($opModulY($opAdditY($getArrayValue(B,new Object[]{1,0}),1),3));
          $line=58;
          Object b=$fix($getArrayValue(B,new Object[]{1,1}));
          $line=60;
          if (($opEqualY(n,"num")&&$opEqualY($getArrayValue(B,new Object[]{0}),':'))) {
            $line=61;
            $result="err";
            if (true) break $try;
          }
          else {
            $line=63;
            if ($opEqualY(n,b)) {
              $line=64;
              $result="num";
              if (true) break $try;
            }
            else {
              $line=65;
              if (($opEqualY(a,0)&&$opMembrY(n,alf))) {
                $line=66;
                $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,b)));
                if (true) break $try;
              }
              else {
                $line=67;
                if (($opEqualY(a,1)&&!$opMembrY(n,alf))) {
                  $line=68;
                  $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                  if (true) break $try;
                }
                else {
                  $line=69;
                  if (($opEqualY(a,2)&&!$opMembrY(n,alf))) {
                    $line=70;
                    $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                    if (true) break $try;
                  }
                  else {
                    $line=71;
                    if ($opEqualY(n,'#')) {
                      $line=72;
                      $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                      if (true) break $try;
                    }
                    else {
                      $line=73;
                      if (($opEqualY(a,1)&&$opEqualY($getArrayValue(B,new Object[]{0}),P2Deco.backToDown(n)))) {
                        $line=74;
                        $result="err";
                        if (true) break $try;
                      }
                      else {
                        $line=75;
                        if (($opEqualY(a,2)&&$opEqualY($getArrayValue(B,new Object[]{0}),P2Deco.toDown(n)))) {
                          $line=76;
                          $result="err";
                          if (true) break $try;
                        }
                        else {
                          $line=78;
                          $result="err";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=81;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=84;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=85;
        $result="";
        if (true) break $try;
      }
      else {
        $line=86;
        if ($opEqualY(A,'I')) {
          $line=87;
          $result=n;
          if (true) break $try;
        }
        else {
          $line=89;
          $result="";
          if (true) break $try;
        }
      }
      $line=91;
      $rethrow(new RuntimeException("The function \"h(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"h",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v3, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object A=$v4.next();
      Object B=$v4.next();
      $line=94;
      if ((($opEqualY(A,"")||$bool((!$opMembrY(A,alf)&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
        $line=95;
        $result="";
        if (true) break $try;
      }
      else {
        $line=96;
        if ($opMembrY(A,alf)) {
          $line=97;
          if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
            $line=98;
            $result=':';
            if (true) break $try;
          }
          else {
            $line=99;
            if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
              $line=100;
              $result=n;
              if (true) break $try;
            }
            else {
              $line=102;
              $result="";
              if (true) break $try;
            }
          }
        }
        else {
          $line=105;
          if ($opEqualY(n,':')) {
            $line=106;
            $result="";
            if (true) break $try;
          }
          else {
            $line=107;
            if ($opEqualY(n,$opIntvlY('0','4'))) {
              $line=108;
              $result='$';
              if (true) break $try;
            }
            else {
              $line=109;
              if ($opEqualY(n,$getArrayValue(A,new Object[]{0}))) {
                $line=110;
                $result=$getArrayValue(A,new Object[]{1});
                if (true) break $try;
              }
              else {
                $line=111;
                if ($opEqualY(n,$getArrayValue(A,new Object[]{1}))) {
                  $line=112;
                  $result=$getArrayValue(A,new Object[]{0});
                  if (true) break $try;
                }
                else {
                  $line=113;
                  if ((!$opMembrY(n,A)&&$opEqualY(n,'#'))) {
                    $line=114;
                    $result=$getArrayValue(B,new Object[]{0});
                    if (true) break $try;
                  }
                  else {
                    $line=115;
                    if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),1))) {
                      $line=116;
                      $result=P2Deco.backToDown(n);
                      if (true) break $try;
                    }
                    else {
                      $line=117;
                      if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),2))) {
                        $line=118;
                        $result=P2Deco.toDown(n);
                        if (true) break $try;
                      }
                      else {
                        $line=120;
                        $result=n;
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=123;
      $rethrow(new RuntimeException("The function \"h(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=126;
      $result="";
      if (true) break $try;
      $line=127;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"g",$line);
    }
    return $result;
  }
  public static Object backToDown(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=130;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=131;
      r=$cast(Character.class,$fix($opAdditY($opAdditY($opModulY($opSubtrY($opSubtrY(n,'a'),1),26),32),'a')));
      $line=132;
      $result=r;
      if (true) break $try;
      $line=133;
      $rethrow(new RuntimeException("The function \"backToDown(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"backToDown",$line);
    }
    return $result;
  }
  public static Object toDown(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=136;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=137;
      r=$cast(Character.class,$fix($opAdditY($opAdditY($opSubtrY(n,'a'),32),'a')));
      $line=138;
      $result=r;
      if (true) break $try;
      $line=139;
      $rethrow(new RuntimeException("The function \"toDown(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"toDown",$line);
    }
    return $result;
  }
}
