// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2Deco.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2Deco {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object M=null;
  public static Object alf=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=9;
      Object decoder=$fix(P2Deco.createDecoder());
      $line=15;
      Utilities.test($cast(gold.structures.automaton.IAutomaton.class,decoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"main",$line);
    }
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=20;
      M=$fix($opIntvlY('A','D'));
      $line=21;
      alf=$fix($opIntvlY('a','d'));
      $line=22;
      Object A=$fix($opUnionY(alf,GCollections.asSet("",'#')));
      $line=23;
      Object AA=$fix($opUnionY(A,M));
      $line=24;
      Object B=$fix($opCartsY(new Object[]{$opIntvlY(0,2),$opIntvlY(0,4)}));
      $line=25;
      Object C=$fix($opUnionY($opCartsY(new Object[]{A,B}),GCollections.asSet(GCollections.asList(':',GCollections.asList(1,0)))));
      $line=26;
      Object D=$fix($opCartsY(new Object[]{A,A}));
      $line=27;
      Object Q=$fix($opUnionY($opUnionY(D,$opCartsY(new Object[]{D,C})),GCollections.asSet('I',"num","err")));
      $line=28;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opUnionY(alf,GCollections.asSet(':')),GCollections.asSet('#')),$opIntvlY('A','Z')),$opIntvlY('0','4')));
      $line=29;
      Object \u03A3_=$fix($opUnionY($opUnionY(alf,GCollections.asSet(':')),GCollections.asSet('$')));
      $line=30;
      Object q_0=$fix('I');
      $line=31;
      Object F=$fix(GCollections.asSet("num"));
      $line=33;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(P2Deco.class,"\u03B4"),new GMethod(P2Deco.class,"g"),new GMethod(P2Deco.class,"h")});
      if (true) break $try;
      $line=34;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=39;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=40;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=41;
        if ($opEqualY(A,'I')) {
          $line=42;
          $result=GCollections.asList(n,"");
          if (true) break $try;
        }
        else {
          $line=43;
          if (($opEqualY(A,"err")||$opEqualY(A,"num"))) {
            $line=44;
            $result="err";
            if (true) break $try;
          }
        }
      }
      $line=46;
      $rethrow(new RuntimeException("The function \"\u03B4(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object A=$v2.next();
      Object B=$v2.next();
      $line=49;
      if (((($opMembrY(A,M)||$opMembrY(B,M))||$opEqualY(A,'#'))||$opEqualY(B,'#'))) {
        $line=50;
        $result="err";
        if (true) break $try;
      }
      else {
        $line=51;
        if ((($opEqualY(A,"")||$bool(((!$opMembrY(A,alf)&&$opGreatY($opAbsolY(A),1))&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
          $line=52;
          $result="err";
          if (true) break $try;
        }
        else {
          $line=53;
          if ($opMembrY(A,alf)) {
            $line=54;
            if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
              $line=55;
              $result=GCollections.asList(GCollections.asList(A,B),GCollections.asList(':',GCollections.asList(1,0)));
              if (true) break $try;
            }
            else {
              $line=56;
              if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
                $line=57;
                if (!$opEqualY(n,'#')) {
                  $line=58;
                  $result=GCollections.asList(A,n);
                  if (true) break $try;
                }
                else {
                  $line=60;
                  $result="err";
                  if (true) break $try;
                }
              }
              else {
                $line=63;
                $result="err";
                if (true) break $try;
              }
            }
          }
          else {
            $line=66;
            Object a=$fix($opModulY($opAdditY($getArrayValue(B,new Object[]{1,0}),1),3));
            $line=67;
            Object b=$fix($getArrayValue(B,new Object[]{1,1}));
            $line=69;
            if (($opEqualY(n,"num")&&$opEqualY($getArrayValue(B,new Object[]{0}),':'))) {
              $line=70;
              $result="err";
              if (true) break $try;
            }
            else {
              $line=71;
              if ($opEqualY(n,$getArrayValue(A,new Object[]{0}))) {
                $line=72;
                $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                if (true) break $try;
              }
              else {
                $line=73;
                if ($opEqualY(n,$getArrayValue(A,new Object[]{1}))) {
                  $line=74;
                  $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                  if (true) break $try;
                }
                else {
                  $line=75;
                  if (($opEqualY(n,P2Deco.toUpper($getArrayValue(A,new Object[]{0})))&&$opEqualY(a,2))) {
                    $line=76;
                    $result="err";
                    if (true) break $try;
                  }
                  else {
                    $line=77;
                    if (($opEqualY(n,P2Deco.nextToUpper($getArrayValue(A,new Object[]{0})))&&$opEqualY(a,1))) {
                      $line=78;
                      $result="err";
                      if (true) break $try;
                    }
                    else {
                      $line=79;
                      if (($opEqualY(n,P2Deco.toUpper($getArrayValue(A,new Object[]{1})))&&$opEqualY(a,2))) {
                        $line=80;
                        $result="err";
                        if (true) break $try;
                      }
                      else {
                        $line=81;
                        if (($opEqualY(n,P2Deco.nextToUpper($getArrayValue(A,new Object[]{1})))&&$opEqualY(a,1))) {
                          $line=82;
                          $result="err";
                          if (true) break $try;
                        }
                        else {
                          $line=84;
                          if ($opEqualY(n,b)) {
                            $line=85;
                            $result="num";
                            if (true) break $try;
                          }
                          else {
                            $line=87;
                            if (($bool(($opEqualY(n,'#')||$opEqualY(n,$opIntvlY('0','4'))))&&$opEqualY($getArrayValue(B,new Object[]{0}),':'))) {
                              $line=88;
                              $result="err";
                              if (true) break $try;
                            }
                            else {
                              $line=90;
                              if (($opEqualY(a,0)&&$opMembrY(n,alf))) {
                                $line=91;
                                $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,b)));
                                if (true) break $try;
                              }
                              else {
                                $line=93;
                                if (($opEqualY(a,1)&&$opMembrY(n,M))) {
                                  $line=94;
                                  $result=GCollections.asList(A,GCollections.asList(P2Deco.backToDown(n),GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                                  if (true) break $try;
                                }
                                else {
                                  $line=96;
                                  if (($opEqualY(a,2)&&$opMembrY(n,M))) {
                                    $line=97;
                                    $result=GCollections.asList(A,GCollections.asList(P2Deco.toDown(n),GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=99;
                                    if ($opEqualY(n,'#')) {
                                      $line=100;
                                      $result=GCollections.asList(A,GCollections.asList(n,GCollections.asList(a,$opModulY($opAdditY(b,1),5))));
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=102;
                                      if (($opEqualY(a,1)&&$opEqualY($getArrayValue(B,new Object[]{0}),P2Deco.backToDown(n)))) {
                                        $line=103;
                                        $result="err";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=105;
                                        if (($opEqualY(a,2)&&$opEqualY($getArrayValue(B,new Object[]{0}),P2Deco.toDown(n)))) {
                                          $line=106;
                                          $result="err";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=109;
                                          $result="err";
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=112;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object A, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=115;
      if (($opEqualY(A,'I')&&!$opMembrY(n,alf))) {
        $line=116;
        $result="";
        if (true) break $try;
      }
      else {
        $line=117;
        if ($opEqualY(A,'I')) {
          $line=118;
          $result=n;
          if (true) break $try;
        }
        else {
          $line=120;
          $result="";
          if (true) break $try;
        }
      }
      $line=122;
      $rethrow(new RuntimeException("The function \"h(A:Object,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"h",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v3, Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object A=$v4.next();
      Object B=$v4.next();
      $line=125;
      if ((($opEqualY(A,"")||$bool((!$opMembrY(A,alf)&&$bool(($opEqualY($getArrayValue(A,new Object[]{0}),"")||$opEqualY($getArrayValue(A,new Object[]{1}),""))))))||$bool(((!$opMembrY(B,alf)&&$opGreatY($opAbsolY(B),1))&&$opEqualY($getArrayValue(B,new Object[]{0}),""))))) {
        $line=126;
        $result="";
        if (true) break $try;
      }
      else {
        $line=127;
        if ($opMembrY(A,alf)) {
          $line=128;
          if (($opMembrY(B,alf)&&$opEqualY(n,':'))) {
            $line=129;
            $result=':';
            if (true) break $try;
          }
          else {
            $line=130;
            if ((!$opMembrY(B,alf)&&$opMembrY(n,alf))) {
              $line=131;
              $result=n;
              if (true) break $try;
            }
            else {
              $line=133;
              $result="";
              if (true) break $try;
            }
          }
        }
        else {
          $line=136;
          if ($opEqualY(n,':')) {
            $line=137;
            $result="";
            if (true) break $try;
          }
          else {
            $line=138;
            if ($opEqualY(n,$opIntvlY('0','4'))) {
              $line=139;
              $result='$';
              if (true) break $try;
            }
            else {
              $line=140;
              if ($opEqualY(n,$getArrayValue(A,new Object[]{0}))) {
                $line=141;
                $result=$getArrayValue(A,new Object[]{1});
                if (true) break $try;
              }
              else {
                $line=142;
                if ($opEqualY(n,$getArrayValue(A,new Object[]{1}))) {
                  $line=143;
                  $result=$getArrayValue(A,new Object[]{0});
                  if (true) break $try;
                }
                else {
                  $line=144;
                  if ($opEqualY(n,'#')) {
                    $line=145;
                    $result=$getArrayValue(B,new Object[]{0});
                    if (true) break $try;
                  }
                  else {
                    $line=146;
                    if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),1))) {
                      $line=147;
                      $result=P2Deco.backToDown(n);
                      if (true) break $try;
                    }
                    else {
                      $line=148;
                      if (((!$opMembrY(n,A)&&!$opEqualY(n,$getArrayValue(B,new Object[]{0})))&&$opEqualY($getArrayValue(B,new Object[]{1,0}),2))) {
                        $line=149;
                        $result=P2Deco.toDown(n);
                        if (true) break $try;
                      }
                      else {
                        $line=151;
                        $result=n;
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=154;
      $rethrow(new RuntimeException("The function \"h(\u27E8A,B\u27E9:java.lang.Iterable,n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=157;
      $result="";
      if (true) break $try;
      $line=158;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"g",$line);
    }
    return $result;
  }
  public static Object backToDown(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=161;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=162;
      r=$cast(Character.class,$fix($opAdditY($opAdditY($opModulY($opSubtrY($opSubtrY(n,'a'),1),26),32),'a')));
      $line=163;
      $result=r;
      if (true) break $try;
      $line=164;
      $rethrow(new RuntimeException("The function \"backToDown(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"backToDown",$line);
    }
    return $result;
  }
  public static Object toDown(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=167;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=168;
      r=$cast(Character.class,$fix($opAdditY($opAdditY($opSubtrY(n,'a'),32),'a')));
      $line=169;
      $result=r;
      if (true) break $try;
      $line=170;
      $rethrow(new RuntimeException("The function \"toDown(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"toDown",$line);
    }
    return $result;
  }
  public static Object nextToUpper(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=173;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=174;
      r=$cast(Character.class,$fix($opAdditY($opSubtrY($opModulY($opAdditY($opSubtrY(n,'a'),1),26),32),'a')));
      $line=175;
      $result=r;
      if (true) break $try;
      $line=176;
      $rethrow(new RuntimeException("The function \"nextToUpper(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"nextToUpper",$line);
    }
    return $result;
  }
  public static Object toUpper(Object n) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=179;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=180;
      r=$cast(Character.class,$fix($opAdditY($opSubtrY($opSubtrY(n,'a'),32),'a')));
      $line=181;
      $result=r;
      if (true) break $try;
      $line=182;
      $rethrow(new RuntimeException("The function \"toUpper(n:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2Deco.class,"toUpper",$line);
    }
    return $result;
  }
}
